plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - lib/pgoutput/client/commands.rb

Metrics/AbcSize:
  Max: 28

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 110

Minitest/MultipleAssertions:
  Max: 12
