module Pgoutput
  module Client
    class SlotStatusData < Data
      attr_reader slot_name: String
      attr_reader plugin: String?
      attr_reader slot_type: String
      attr_reader database: String?
      attr_reader active: bool
      attr_reader active_pid: Integer?
      attr_reader catalog_xmin: String?
      attr_reader restart_lsn: String?
      attr_reader confirmed_flush_lsn: String?
      attr_reader retained_wal_bytes: Integer?
      attr_reader wal_status: String?
      attr_reader safe_wal_size: Integer?
      attr_reader inactive_since: String?
      attr_reader conflicting: bool?
      attr_reader invalidation_reason: String?

      def self.new: (
        slot_name: String,
        plugin: String?,
        slot_type: String,
        database: String?,
        active: bool,
        active_pid: Integer?,
        catalog_xmin: String?,
        restart_lsn: String?,
        confirmed_flush_lsn: String?,
        retained_wal_bytes: Integer?,
        wal_status: String?,
        safe_wal_size: Integer?,
        inactive_since: String?,
        conflicting: bool?,
        invalidation_reason: String?
      ) -> instance
    end

    class SlotStatus < SlotStatusData
      def self.from_catalog: (Hash[(String | Symbol), untyped] attributes) -> SlotStatus
    end
  end
end
